// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQE6o87ZCqXaE8YDbhU-XYO_J_JZ3c5Fo',
    appId: '1:38653644249:web:e1559fcf3ac8921cb29dc8',
    messagingSenderId: '38653644249',
    projectId: 'browsein-40d00',
    authDomain: 'browsein-40d00.firebaseapp.com',
    storageBucket: 'browsein-40d00.firebasestorage.app',
    measurementId: 'G-Q4BX47E0DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7GbesUyVQcwBvg7qQ83DDpmxXak-gNo',
    appId: '1:38653644249:android:8a2d62ddd49cd030b29dc8',
    messagingSenderId: '38653644249',
    projectId: 'browsein-40d00',
    storageBucket: 'browsein-40d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gbpVFBa9lOJdwrfmrgU4ifGQnRilpEo',
    appId: '1:38653644249:ios:64346baa9bd262bab29dc8',
    messagingSenderId: '38653644249',
    projectId: 'browsein-40d00',
    storageBucket: 'browsein-40d00.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gbpVFBa9lOJdwrfmrgU4ifGQnRilpEo',
    appId: '1:38653644249:ios:64346baa9bd262bab29dc8',
    messagingSenderId: '38653644249',
    projectId: 'browsein-40d00',
    storageBucket: 'browsein-40d00.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaCloneFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQE6o87ZCqXaE8YDbhU-XYO_J_JZ3c5Fo',
    appId: '1:38653644249:web:26a120df2d8559efb29dc8',
    messagingSenderId: '38653644249',
    projectId: 'browsein-40d00',
    authDomain: 'browsein-40d00.firebaseapp.com',
    storageBucket: 'browsein-40d00.firebasestorage.app',
    measurementId: 'G-0363LFJ7W3',
  );
}
